Repository microsoft/superbenchmark, pull requests merged in 2021-11, with the labels that each got.

#235 Bug - Fix configuration for memory bandwidth test
  .azure-pipelines/cpu-unit-test.yml
  superbench/config/amd_mi100_hpe.yaml
  superbench/config/amd_mi100_z53.yaml
  superbench/config/azure_ndv4.yaml
  superbench/config/default.yaml
Labels: bug

#237 Docs: Update docs to add ORT AMD benchmarks based on docker
  docs/superbench-config.mdx
  docs/user-tutorial/benchmarks/docker-benchmarks.md
  website/sidebars.js
Labels: documentation

#215 Benchmarks: Add Benchmark - Add ib traffic validation distributed benchmark
  examples/benchmarks/ib_validation_performance.py
  superbench/benchmarks/micro_benchmarks/__init__.py
  superbench/benchmarks/micro_benchmarks/ib_validation_performance.py
  superbench/benchmarks/micro_benchmarks/ib_validation_performance/CMakeLists.txt
  superbench/benchmarks/return_code.py
  tests/benchmarks/micro_benchmarks/test_ib_traffic_performance.py
Labels: benchmarks, micro-benchmarks

#238 Docs: Update docs to add network benchmarks for tcp and gpcnet
  docs/user-tutorial/benchmarks/micro-benchmarks.md
Labels: documentation

#236 Benchmarks - Add TensorRT inference benchmark
  .gitignore
  docs/user-tutorial/benchmarks/micro-benchmarks.md
  examples/benchmarks/tensorrt_inference_performance.py
  superbench/benchmarks/micro_benchmarks/__init__.py
  superbench/benchmarks/micro_benchmarks/tensorrt_inference_performance.py
  tests/benchmarks/micro_benchmarks/test_tensorrt_inference_performance.py
  tests/data/tensorrt_inference.log
  tests/helper/decorator.py
Labels: benchmarks, micro-benchmarks

#244 Benchmarks: Fix Typo - Fix typo in description of kernel launch overhead example
  examples/benchmarks/kernel_launch_overhead.py
Labels: benchmarks

#246 Docs: Update ib validation microbenchmark metrics
  docs/user-tutorial/benchmarks/micro-benchmarks.md
Labels: documentation
