Repository microsoft/superbenchmark, pull requests merged in 2022-08, with the labels that each got.

#378 Analyzer - Add failure check feature in data diagnosis
  superbench/analyzer/data_diagnosis.py
  superbench/analyzer/diagnosis_rule_op.py
  superbench/analyzer/diagnosis_summary.xlsx
  superbench/analyzer/file_handler.py
  tests/analyzer/test_data_diagnosis.py
  tests/analyzer/test_ruleop.py
  tests/data/diagnosis_summary.html
  tests/data/diagnosis_summary.json
  tests/data/diagnosis_summary.jsonl
  tests/data/diagnosis_summary.md
  tests/data/diagnosis_summary.xlsx
Labels: tool

#385 Runner - Fix minimum timeout
  superbench/runner/runner.py
Labels: bug

#382 Analyzer: Rename fields in json of data diagnosis to be more readable
  superbench/analyzer/data_diagnosis.py
  tests/data/diagnosis_summary.json
Labels: tool

#381 Auto generate ibstat file for IB performance validation under topo-aware …
  .azure-pipelines/cuda-unit-test.yml
  dockerfile/cuda11.1.1.dockerfile
  dockerfile/rocm5.0.x.dockerfile
  dockerfile/rocm5.1.x.dockerfile
  setup.py
  superbench/common/utils/topo_aware.py
Labels: benchmarks

#387 Update Python setup for require packages
  .azure-pipelines/cpu-unit-test.yml
  .azure-pipelines/cuda-unit-test.yml
  .devcontainer/post-create-command.sh
  dockerfile/cuda11.1.1.dockerfile
  dockerfile/rocm5.0.x.dockerfile
  dockerfile/rocm5.1.x.dockerfile
  docs/developer-guides/development.md
  setup.py
Labels: dependencies

#388 Analyzer - Add support for both jsonl and json format in data diagnosis
  docs/cli.md
  docs/user-tutorial/data-diagnosis.md
  superbench/analyzer/data_diagnosis.py
  superbench/cli/_help.py
  superbench/cli/_result_handler.py
  tests/analyzer/test_data_diagnosis.py
  tests/data/diagnosis_summary_json.json
Labels: tool

#392 Analyzer - Add support to store values of metrics in data diagnosis
  superbench/analyzer/data_diagnosis.py
  superbench/analyzer/diagnosis_rule_op.py
  tests/analyzer/test_data_diagnosis.py
Labels: tool

#396 Enable latency test in ib traffic validation distributed benchmark
  superbench/benchmarks/micro_benchmarks/ib_validation_performance.py
  superbench/benchmarks/micro_benchmarks/ib_validation_performance/ib_validation_performance.cc
  tests/benchmarks/micro_benchmarks/test_ib_traffic_performance.py
Labels: benchmarks

#398 Update apt packages in dockerfile
  dockerfile/cuda11.1.1.dockerfile
  dockerfile/rocm5.0.x.dockerfile
  dockerfile/rocm5.1.x.dockerfile
Labels: dependencies

#404 Upgrade colorlog for NO_COLOR support
  setup.py
  superbench/common/utils/logging.py
Labels: enhancement, utils, dependencies
