Repository microsoft/superbenchmark, pull requests merged in 2022-04, with the labels that each got.

#333 Benchmarks: Add Feature - Provide option to save raw data into file.
  docs/superbench-config.mdx
  superbench/benchmarks/base.py
  superbench/benchmarks/docker_benchmarks/rocm_onnxruntime_performance.py
  superbench/benchmarks/micro_benchmarks/cpu_memory_bw_latency_performance.py
  superbench/benchmarks/micro_benchmarks/cublas_function.py
  superbench/benchmarks/micro_benchmarks/cuda_gemm_flops_performance.py
  superbench/benchmarks/micro_benchmarks/cuda_memory_bw_performance.py
  superbench/benchmarks/micro_benchmarks/cuda_nccl_bw_performance.py
  superbench/benchmarks/micro_benchmarks/cudnn_function.py
  superbench/benchmarks/micro_benchmarks/disk_performance.py
  superbench/benchmarks/micro_benchmarks/gpcnet_performance.py
  superbench/benchmarks/micro_benchmarks/gpu_burn_test.py
  superbench/benchmarks/micro_benchmarks/gpu_copy_bw_performance.py
  superbench/benchmarks/micro_benchmarks/ib_loopback_performance.py
  superbench/benchmarks/micro_benchmarks/ib_validation_performance.py
  superbench/benchmarks/micro_benchmarks/kernel_launch_overhead.py
  superbench/benchmarks/micro_benchmarks/micro_base.py
  superbench/benchmarks/micro_benchmarks/rocm_gemm_flops_performance.py
  superbench/benchmarks/micro_benchmarks/rocm_memory_bw_performance.py
  superbench/benchmarks/micro_benchmarks/tcp_connectivity.py
  superbench/benchmarks/micro_benchmarks/tensorrt_inference_performance.py
  superbench/benchmarks/model_benchmarks/model_base.py
  superbench/benchmarks/result.py
  superbench/executor/executor.py
  tests/benchmarks/docker_benchmarks/test_docker_base.py
  tests/benchmarks/docker_benchmarks/test_rocm_onnxruntime_performance.py
  tests/benchmarks/micro_benchmarks/test_gemm_flops_performance_base.py
  tests/benchmarks/micro_benchmarks/test_memory_bw_performance_base.py
  tests/benchmarks/micro_benchmarks/test_micro_base.py
  tests/benchmarks/micro_benchmarks/test_tensorrt_inference_performance.py
  tests/benchmarks/model_benchmarks/test_model_base.py
  tests/benchmarks/test_registry.py
  tests/benchmarks/test_result.py
Labels: enhancement, benchmarks

#335 CLI - Integrage result summary and update output format of data diagnosis
  docs/cli.md
  superbench/cli/_commands.py
  superbench/cli/_help.py
  superbench/cli/_result_handler.py
  tests/cli/test_sb.py
Labels: CLI

#337 Docs - Add usage for result summary
  docs/user-tutorial/result-summary.md
  website/sidebars.js
Labels: documentation

#336 Analyzer: Add Feature - Output results of all nodes in data diagnosis
  superbench/analyzer/data_diagnosis.py
  tests/analyzer/test_data_diagnosis.py
  tests/data/diagnosis_summary.json
Labels: tool

#339 CLI - Integrate output all nodes diagnosis results
  docs/cli.md
  superbench/cli/_commands.py
  superbench/cli/_help.py
  superbench/cli/_result_handler.py
  tests/cli/test_sb.py
Labels: CLI

#338 Benchmarks: Add Benchmark - Add FAMBench based on docker benchmark
  examples/benchmarks/fambench.py
  superbench/benchmarks/docker_benchmarks/__init__.py
  superbench/benchmarks/docker_benchmarks/fambench.py
  tests/benchmarks/docker_benchmarks/test_fambench.py
Labels: benchmarks, docker-benchmarks

#341 Docs - Update link to cli.md
  docs/user-tutorial/result-summary.md
Labels: documentation

#343 Bug - Force to fix ort version as '1.10.0'
  setup.py
Labels: bug

#345 Bug - Support no matching rules and unify the output name in result_summary
  docs/user-tutorial/result-summary.md
  superbench/analyzer/result_summary.py
  tests/analyzer/test_result_summary.py
Labels: bug, tool

#344 Analyzer - Support regex in annotations of benchmark naming for metrics in rules
  superbench/analyzer/rule_base.py
Labels: tool

#342 Bug - Fix bugs in sync results on root rank for e2e model benchmarks
  superbench/benchmarks/model_benchmarks/model_base.py
  superbench/benchmarks/model_benchmarks/pytorch_base.py
  tests/benchmarks/model_benchmarks/test_pytorch_base.py
Labels: bug

#348 Docs - Upgrade version and release note
  README.md
  docs/getting-started/installation.mdx
  docs/getting-started/run-superbench.md
  docs/superbench-config.mdx
  docs/user-tutorial/container-images.mdx
  docs/user-tutorial/data-diagnosis.md
  docs/user-tutorial/result-summary.md
  superbench/__init__.py
  superbench/config/amd_mi100_hpe.yaml
  superbench/config/amd_mi100_z53.yaml
  superbench/config/azure/inference/nc64as_t4_v3.yaml
  superbench/config/azure/inference/nc96ads_a100_v4.yaml
  superbench/config/azure/inference/nv18ads_a10_v5.yaml
  superbench/config/azure_ndmv4.yaml
  superbench/config/azure_ndv4.yaml
  superbench/config/default.yaml
  website/blog/2022-04-28-release-0-5.md
  website/docusaurus.config.js
  website/package-lock.json
  website/package.json
Labels: documentation, release

#350 Release - SuperBench v0.5.0
  README.md
  docs/getting-started/installation.mdx
  docs/getting-started/run-superbench.md
  docs/superbench-config.mdx
  docs/user-tutorial/container-images.mdx
  docs/user-tutorial/data-diagnosis.md
  docs/user-tutorial/result-summary.md
  setup.py
  superbench/__init__.py
  superbench/analyzer/result_summary.py
  superbench/analyzer/rule_base.py
  superbench/benchmarks/model_benchmarks/model_base.py
  superbench/benchmarks/model_benchmarks/pytorch_base.py
  superbench/benchmarks/model_benchmarks/pytorch_bert.py
  superbench/benchmarks/model_benchmarks/pytorch_cnn.py
  superbench/benchmarks/model_benchmarks/pytorch_gpt2.py
  superbench/benchmarks/model_benchmarks/pytorch_lstm.py
  superbench/config/amd_mi100_hpe.yaml
  superbench/config/amd_mi100_z53.yaml
  superbench/config/azure/inference/nc64as_t4_v3.yaml
  superbench/config/azure/inference/nc96ads_a100_v4.yaml
  superbench/config/azure/inference/nv18ads_a10_v5.yaml
  superbench/config/azure_ndmv4.yaml
  superbench/config/azure_ndv4.yaml
  superbench/config/default.yaml
  tests/analyzer/test_result_summary.py
  tests/benchmarks/model_benchmarks/test_pytorch_base.py
  website/blog/2022-04-28-release-0-5.md
  website/docusaurus.config.js
  website/package-lock.json
  website/package.json
Labels: release
