Repository microsoft/superbenchmark, pull requests merged in 2022-03, with the labels that each got.

#322 Benchmarks - Keep BatchNorm as fp32 for pytorch cnn models cast to fp16
  superbench/benchmarks/model_benchmarks/pytorch_cnn.py
Labels: benchmarks, model-benchmarks

#321 Analyzer: Revise - Abstract RuleBase from DataDiagnosis
  superbench/analyzer/__init__.py
  superbench/analyzer/data_diagnosis.py
  superbench/analyzer/rule_base.py
  tests/analyzer/test_data_diagnosis.py
  tests/analyzer/test_rulebase.py
Labels: tool

#327 Bug - Fix env path to absolute path
  superbench/runner/playbooks/check_env.yaml
  superbench/runner/runner.py
Labels: bug

#328 Bug: Executor - fix bug in result writing to files for mpi mode
  superbench/executor/executor.py
Labels: bug

#330 Bug: Benchmarks - remove fp16 samples type converting time for cnn and lstm models
  superbench/benchmarks/model_benchmarks/pytorch_cnn.py
  superbench/benchmarks/model_benchmarks/pytorch_lstm.py
Labels: bug

#329 Config - Add inference config for NC A100 and NV A10 series
  .mypy.ini
  superbench/config/azure/inference/nc96ads_a100_v4.yaml
  superbench/config/azure/inference/nv18ads_a10_v5.yaml
Labels: configuration

#332 Bug: Benchmarks - remove fp16 samples type converting time for training cnn and lstm inference
  superbench/benchmarks/model_benchmarks/pytorch_cnn.py
  superbench/benchmarks/model_benchmarks/pytorch_lstm.py
Labels: bug

#320 Analyzer: Add feature - Add result summary in excel,md,html format
  superbench/analyzer/__init__.py
  superbench/analyzer/data_analysis.py
  superbench/analyzer/data_diagnosis.py
  superbench/analyzer/file_handler.py
  superbench/analyzer/result_summary.py
  superbench/analyzer/summary_op.py
  tests/analyzer/test_data_analysis.py
  tests/analyzer/test_data_diagnosis.py
  tests/analyzer/test_file_handler.py
  tests/analyzer/test_result_summary.py
  tests/analyzer/test_summary_rules.yaml
  tests/analyzer/test_summaryop.py
  tests/data/results_summary.html
  tests/data/results_summary.md
  tests/data/results_summary.xlsx
Labels: tool
