Repository microsoft/superbenchmark, pull requests merged in 2023-02, with the labels that each got.

#476 Dockerfile: Remove fixed rccl version in rocm5.1.x docker file
  dockerfile/rocm5.1.x.dockerfile
Labels: containers

#475 Executor - Support SuperBench Executor running on Windows
  superbench/common/utils/lazy_import.py
  superbench/runner/__init__.py
  superbench/runner/runner.py
Labels: enhancement, executor

#473 Adding Stream Benchmark
  dockerfile/cuda11.1.1.dockerfile
  dockerfile/cuda11.8.dockerfile
  dockerfile/rocm5.0.x.dockerfile
  dockerfile/rocm5.1.x.dockerfile
  docs/user-tutorial/benchmarks/micro-benchmarks.md
  examples/benchmarks/cpu_stream_performance.py
  superbench/benchmarks/micro_benchmarks/__init__.py
  superbench/benchmarks/micro_benchmarks/cpu_stream_performance.py
  tests/benchmarks/micro_benchmarks/test_cpu_stream_performance.py
  tests/data/streamResult.log
  third_party/Makefile
  third_party/stream-tests/Makefile
Labels: benchmarks, micro-benchmarks

#481 CI/CD - Free disk space in GitHub Action VHD
  .github/workflows/build-image.yml
Labels: CI/CD

#480 Benchmarks: Build Pipeline - Add suppport for cpu-only perftest in makefile
  third_party/Makefile
Labels: enhancement, benchmarks, dependencies

#479 Benchmarks: Revision - Support flexible warmup and non-random data initialization in cublas-benchmark
  superbench/benchmarks/micro_benchmarks/cublas_function.py
  superbench/benchmarks/micro_benchmarks/cublas_function/cublas_benchmark.h
  superbench/benchmarks/micro_benchmarks/cublas_function/cublas_function.h
  superbench/benchmarks/micro_benchmarks/cublas_function/cublas_function_helper.h
Labels: benchmarks, micro-benchmarks
