Repository microsoft/superbenchmark, pull requests merged in 2023-11, with the labels that each got.

#567 Bug Fix - remove cp ptx file command in gpu burn test
  superbench/benchmarks/micro_benchmarks/gpu_burn_test.py
  tests/benchmarks/micro_benchmarks/test_gpu_burn_test.py
Labels: bug

#578 Benchmarks: Micro benchmark - add initialization options for rocm gemm flops
  superbench/benchmarks/micro_benchmarks/rocm_gemm_flops_performance.py
  tests/benchmarks/micro_benchmarks/test_rocm_gemm_flops_performance.py
Labels: benchmarks, micro-benchmarks

#577 Dockerfile - Upgrade Docker image to CUDA 12.2
  .github/workflows/build-image.yml
  dockerfile/cuda12.2.dockerfile
  setup.py
  superbench/benchmarks/micro_benchmarks/cublas_function/cublas_benchmark.h
Labels: containers

#580 Monitor - Add support for AMD GPU.
  setup.py
  superbench/common/utils/device_manager.py
  superbench/executor/executor.py
Labels: monitor
