Repository microsoft/superbenchmark, pull requests merged in 2023-06, with the labels that each got.

#534 Dockerfile - Add SuperBench Windows Dockerfile
  .github/workflows/build-win.yml
  Makefile
  dockerfile/directx/enable-graphics-apis.py
  dockerfile/directx/install-components.bat
  dockerfile/directx/mini_vsconfig.json
  dockerfile/directx12.dockerfile
  superbench/benchmarks/build.bat
Labels: CI/CD

#488 Benchmarks: Add benchmark - Add source code of DirectXGPUCoreFLOPs microbenchmark
  .gitignore
  superbench/benchmarks/micro_benchmarks/directx_gemm_flops_performance/BenchmarkOptions.h
  superbench/benchmarks/micro_benchmarks/directx_gemm_flops_performance/GPUCore.cpp
  superbench/benchmarks/micro_benchmarks/directx_gemm_flops_performance/GPUCore.h
  superbench/benchmarks/micro_benchmarks/directx_gemm_flops_performance/GPUCore.vcxproj
  superbench/benchmarks/micro_benchmarks/directx_gemm_flops_performance/Main.cpp
  superbench/benchmarks/micro_benchmarks/directx_gemm_flops_performance/packages.config
  superbench/benchmarks/micro_benchmarks/directx_third_party/DXSampleHelper.h
  superbench/benchmarks/micro_benchmarks/directx_third_party/d3dx12.h
  superbench/benchmarks/micro_benchmarks/directx_utils/D3D12Timer.cpp
  superbench/benchmarks/micro_benchmarks/directx_utils/D3D12Timer.h
  superbench/benchmarks/micro_benchmarks/directx_utils/Options.h
Labels: micro-benchmarks

#532 Tools - Add runner for sys info and update docs
  docs/cli.md
  docs/user-tutorial/system-config.md
  superbench/cli/_commands.py
  superbench/cli/_handler.py
  superbench/cli/_help.py
  superbench/cli/_node_handler.py
  superbench/runner/runner.py
Labels: tool

#541 Benchmarks - Update result parsing in tensorrt inference
  setup.py
  superbench/benchmarks/micro_benchmarks/_export_torch_to_onnx.py
  superbench/benchmarks/micro_benchmarks/tensorrt_inference_performance.py
  tests/benchmarks/micro_benchmarks/test_tensorrt_inference_performance.py
  tests/data/tensorrt_inference.1.log
  tests/data/tensorrt_inference.2.log
Labels: benchmarks

#544 Doc - Update outdate references in micro-benchmarks.md
  docs/user-tutorial/benchmarks/micro-benchmarks.md
Labels: documentation
