Repository microsoft/superbenchmark, pull requests merged in 2024-08, with the labels that each got.

#635 Bug Fix - Update Docker Exec Command for Persistent HPCX Environment
  dockerfile/cuda12.2.dockerfile
  dockerfile/cuda12.4.dockerfile
  superbench/runner/runner.py
Labels: bug, containers

#638 Bug Fix: Data Diagnosis - Fix bug of failure test and warning of pandas in data diagnosis
  superbench/analyzer/data_analysis.py
  superbench/analyzer/data_diagnosis.py
  superbench/analyzer/diagnosis_rule_op.py
Labels: bug, tool

#636 Bug - Fix issues caused by omegaconf version update
  superbench/executor/executor.py
  superbench/runner/runner.py
  tests/executor/test_executor.py
  tests/runner/test_runner.py
Labels: bug, executor
