Repository microsoft/superbenchmark, pull requests merged in 2024-07, with the labels that each got.

#632 Docs - Add BibTeX in README and repo
  CITATION.bib
  README.md
Labels: documentation

#628 Docs - fix typos
  docs/cli.md
  docs/superbench-config.mdx
Labels: documentation

#634 Benchmarks: Micro benchmarks - add support for NVIDIA L4/L40/L40s GPUs in gemm-flops
  superbench/benchmarks/micro_benchmarks/cuda_common.cmake
  superbench/benchmarks/micro_benchmarks/cuda_gemm_flops_performance.py
  third_party/Makefile
Labels: benchmarks, micro-benchmarks

#633 CI/CD - Fix MSCCL build error in CUDA12.4 docker build pipeline
  .github/workflows/build-image.yml
  dockerfile/rocm5.7.x.dockerfile
  dockerfile/rocm6.0.x.dockerfile
  third_party/Makefile
Labels: CI/CD
