Repository microsoft/superbenchmark, pull requests merged in 2024-11, with the labels that each got.

#659 CI/CD - Update Image Build Pipeline
  .github/workflows/build-image.yml
Labels: CI/CD

#658 Bug Fix - Fix numa error on grace cpu in gpu-copy
  superbench/benchmarks/micro_benchmarks/gpu_copy_performance/gpu_copy.cu
Labels: bug

#660 Dockerfile - Add support for arm64 build
  .github/workflows/build-image.yml
  dockerfile/cuda12.4.dockerfile
  setup.py
  superbench/benchmarks/micro_benchmarks/cpu_stream_performance.py
  superbench/benchmarks/micro_benchmarks/cuda_decode_performance/CMakeLists.txt
  third_party/Makefile
  third_party/stream-tests/Makefile
Labels: containers

#663 Dependency - Bump onnxruntime-gpu version from 1.10.0 to 1.12.0
  setup.py
Labels: dependencies

#662 Benchmarks: micro benchmarks - add general CPU bandwidth and latency benchmark
  superbench/benchmarks/micro_benchmarks/cpu_copy_performance/CMakeLists.txt
  superbench/benchmarks/micro_benchmarks/cpu_copy_performance/cpu_copy.cpp
  superbench/benchmarks/micro_benchmarks/cpu_memory_bw_latency_performance.py
  tests/benchmarks/micro_benchmarks/test_cpu_memory_bw_latency_performance.py
Labels: benchmarks, micro-benchmarks

#670 Docs - Update CODEOWNERS
  .github/CODEOWNERS
Labels: documentation

#669 Benchmarks: micro benchmarks - add nvbandwidth benchmark
  docs/user-tutorial/benchmarks/micro-benchmarks.md
  examples/benchmarks/nvbandwidth.py
  superbench/benchmarks/micro_benchmarks/__init__.py
  superbench/benchmarks/micro_benchmarks/nvbandwidth.py
  tests/benchmarks/micro_benchmarks/test_nvbandwidth.py
  tests/data/nvbandwidth_results.log
Labels: documentation, benchmarks, micro-benchmarks

#671 CI/CD - Upgrade dependency versions in pipeline
  .azure-pipelines/ansible-integration-test.yml
  .azure-pipelines/cpu-unit-test.yml
  .azure-pipelines/cuda-unit-test.yml
  .codecov.yml
  docs/getting-started/installation.mdx
  setup.py
  superbench/benchmarks/base.py
  tests/analyzer/test_summaryop.py
  tests/benchmarks/model_benchmarks/test_pytorch_base.py
Labels: CI/CD

#668 Benchmarks - Add LLaMA-2 Models
  docs/superbench-config.mdx
  docs/user-tutorial/benchmarks/model-benchmarks.md
  examples/benchmarks/pytorch_llama2.py
  setup.py
  superbench/benchmarks/base.py
  superbench/benchmarks/micro_benchmarks/_export_torch_to_onnx.py
  superbench/benchmarks/model_benchmarks/__init__.py
  superbench/benchmarks/model_benchmarks/pytorch_llama.py
  tests/benchmarks/model_benchmarks/test_pytorch_llama.py
Labels: benchmarks, micro-benchmarks, model-benchmarks
