Repository microsoft/superbenchmark, pull requests merged in 2025-02, with the labels that each got.

#684 Setup - Fix installation and lint issues
  setup.py
Labels: test, dependencies

#674 Bug - Fix tensorrt-inference parsing
  superbench/benchmarks/micro_benchmarks/tensorrt_inference_performance.py
Labels: bug, micro-benchmarks

#675 Bugfix - nvbandwidth benchmark need to handle N/A value
  examples/benchmarks/nvbandwidth.py
  superbench/benchmarks/micro_benchmarks/nvbandwidth.py
  superbench/config/default.yaml
  tests/benchmarks/micro_benchmarks/test_nvbandwidth.py
Labels: bug, configuration

#686 Docs - Fix typos in documentation and code files
  superbench/benchmarks/micro_benchmarks/cuda_decode_performance/AppDecPerf.cpp
  superbench/benchmarks/micro_benchmarks/directx_mem_bw_performance/GPUMemRwBw.cpp
  superbench/benchmarks/micro_benchmarks/directx_mem_bw_performance/GPUMemRwBw.h
  superbench/benchmarks/micro_benchmarks/tcp_connectivity.py
Labels: documentation
